version: "3"
services:
  mongo:
    container_name: my-mongo
    image: mongo:4.4.4
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
    - $HOME/docker/volumes/mongo:/data/db

  mongo-express:
    container_name: my-mongo-express
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    depends_on:
      - mongo
