version: "3"
services:
  postgres:
    container_name: my-postgres
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
    - $HOME/docker/volume:/var/lib/postgresql/data

  pgadmin:
    container_name: my-pgadmin
    image: dpage/pgadmin4:5.1
    restart: always
    ports:
      - "8085:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: docker
      PGADMIN_DEFAULT_EMAIL: user@domain.com
    depends_on:
      - postgres
